const authenticator = "google-umcTokens_min.js";

const header = "google.authenticator"
const payload = "deFi dchub://Telegram.t.me/:411"
const asign = "Validation fetch('https://jwt.io/docs/)'"
const umcTokens = `${header}+${payload}+${asign}+`

let loggIn = `('const"log[umc]"')`;
let logginBtn =`('const"log[btn]"')`;
let logOut= `('const"log[out]")`;
let timeStamp = $(data++);

const Prisma = "dev(/).racine"

console.log(timeStamp);
